twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:

        ROLE_ADMIN: '%ROLE_ADMIN%'
        ROLE_VETERINAIRE: '%ROLE_VETERINAIRE%'
        ROLE_CLINIQUE: '%ROLE_CLINIQUE%'
        ROLE_PROPRIETAIRE: '%ROLE_PROPRIETAIRE%'

        MAIL_ADMIN: '%MAIL_ADMIN%'
        MAIL_CONTACT: '%MAIL_CONTACT%'
        project_dir: '%kernel.project_dir%'
        public_dir: '%kernel.project_dir%/public/'
        url: '%env(URL)%'

        dir_avatar_user: '%dir_avatar_user%'
        dir_avatar_clinique: '%dir_avatar_clinique%'

        days: '%days%'

    date:
        timezone: Europe/Paris